### ISSUE TITLE
Configure the design framework

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#10]
Install and setup a certain design framework (the team has decided to use Tailwind CSS) to style all the application screens.
```[tasklist]
### Tasks
- [x] Decide which design framework is going to be used.
- [x] Install and successfully configure and implement the design framework.
- [x] Make a quick test to assure the framework functionality.
```
