### ISSUE TITLE
Design the navigation bar

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#11]
Build the navigation bar into the application general UI and use the selected design framework to style it according to the next sketch:

![Image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1/assets/58612112/71813565-446a-4457-816d-3b4ddc913b9b)

```[tasklist]
### Tasks
- [x] Make the navigation bar sketch and add it to the issue.
- [ ] Build the navbar view.
- [ ] Apply styles to the navbar.
```
