### ISSUE TITLE
Build the home screen and navigation bar

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#12]
Build the home screen view, generate a functional navigation bar and apply the corresponding styles to achieve a attractive UI, all of this according to the next sketch:

![Image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1/assets/58612112/e55b40c2-1e46-4a04-833f-7f5ed17b5f20)

```[tasklist]
### Tasks
- [x] Add the home screen sketch.
- [ ] Code the home screen view.
- [ ] Code the navigation bar view and link.
- [ ] Apply CSS styles to the home screen view and navigation bar.
```
