### ISSUE TITLE
Apply styles to the events CRUD forms

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#13]
Apply styles to each of the events CRUD forms to achieve an attractive system.
```[tasklist]
### Tasks
- [ ] Apply styles to events index page.
- [ ] Apply styles to events show page.
- [ ] Apply styles to events new page.
- [ ] Apply styles to events edit page.
- [ ] Apply styles to events destroy page.
```
