### ISSUE TITLE
Redesign the events CRUD forms

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#16]
Review all the prototype forms layouts in order to design more appropiate UI's for each one of them (the added sketches are design prototypes).

![Image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1/assets/58612112/26fb81b9-f6fe-4478-9dca-e5feeb881808)
![Image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1/assets/58612112/cf986408-1168-4ee4-8814-1b798f47219c)
![Image](https://github.com/BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1/assets/58612112/28d4dfaf-5f48-4e08-8352-f3882e46b57d)

```[tasklist]
### Tasks
- [x] Review and redesign the index screen layout.
- [x] Review and redesign the show screen layout.
- [x] Review and redesign the create screen layout.
- [x] Review and redesign the edit screen layout.
- [x] Review and redesign the destroy screen layout.
```
