### ISSUE TITLE
Review and improve the quality and consistency of the application code

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#17]
Setup the project in order to apply Rubocop, Reek and RubyCritic code analysis to make the code factorization easier, generate the reviews results and make corrections as many as possible.

```[tasklist]
### Tasks
- [x] Setup RuboCop and use it to analyze the application code.
- [x] Erase as many as possible RuboCop warnings.
- [x] Setup Reek and use it to detect any code smells.
- [x] Erase as many as possible smells detected by Reek.
- [x] Setup RubyCritic and run it in order to generate the overall application score.
- [x] Achieve an overall 90 minimum RubyCritic application score.
```
