### ISSUE TITLE
Refactor the application code with code analyzers support

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#18]
Make the necessary application code refactors in order to satisfy the overall community's coding standards.
```[tasklist]
### Tasks
- [ ] Erase as many as possible RuboCop warnings.
- [ ] Erase as many as possible smells detected by Reek.
- [ ] Achieve an overall 90 minimum RubyCritic application score.
```
