### ISSUE TITLE
Create event manager CRUD prototype

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#2]
Create all the events model operations, actions, views and controllers to achieve a functional CRUD system prototype (unstyled and beta UI).

```[tasklist]
### Tasks
- [x] Review the event model and add basic data validationds
- [x] Create the corresponding controller, actions and routes to manage all CRUD operations.
- [x] Define the template views to display the beta forms for CRUD operations.
- [x] Code all the actions in order to achieve the functional CRUD.
```
