### ISSUE TITLE
Evaluate and improve the quality of the test code

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#21]
Use RuboCop, Reek and RubyCritic to review and analyze the code format, structure, smells and overall quality.
```[tasklist]
### Tasks
- [ ] Use RuboCop to review the test code format.
- [ ] Use Reek to detect any smell in test code.
- [ ] Erase as many as possible smells detected by Reek.
- [ ] Erase any test code RuboCop warnings.
- [ ] Use RubyCritic to grade the test code overall quality.
- [ ] Achieve an overall 65 minimum RubyCritic score.
```
