### ISSUE TITLE
Refactor the test code

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#22]
Refactor the test code in order to satisfy general software standards.
```[tasklist]
### Tasks
- [ ] Erase any test code RuboCop warnings.
- [ ] Erase as many as possible smells detected by Reek.
- [ ] Achieve a overall 65 minimum RubyCritic score.
```
