### ISSUE TITLE
Generate the README.md

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#23]
Modify the README.md in order to add general project's description, installation instructions, usage, credits and badges.
```[tasklist]
### Tasks
- [x] Add project's description.
- [x] Add project's installation instructions.
- [x] Add project's usage instructions.
- [x] Add project's credits.
- [x] Add project's badges.
```
