### ISSUE TITLE
Code all the actions in order to achieve the functional CRUD.

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#28]
Generate all the necessary code to make the events CRUD functional.
```[tasklist]
### Tasks
- [ ] Code the index action.
- [ ] Code the show action.
- [ ] Code the new action.
- [ ] Code the create action.
- [ ] Code the edit action.
- [ ] Code the update action.
- [ ] Code the destroy action.
```
