### ISSUE TITLE
Install and successfully config Devise

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#34]
Install Devise gem in Rails project in order to enable a standard user's registration and authentication system building.
```[tasklist]
### Tasks
- [x] Install Devise gem.
- [x] Successfully configure the Devise gem.
- [x] Test Devise functionality.
- [x] Correctly integrate Devise users management into the application navbar.
- [ ] Add a navbar text to indicate if the current user is logged or not.
```
