### ISSUE TITLE
Install and successfully config Active Storage

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#35]
Install the Active Storage service in order to enable images management in the Rails application.
```[tasklist]
### Tasks
- [x] Install Active Storage.
- [x] Config Active Storage to save images in a local environment.
- [x] Add a Event model migration to add a image field support.
- [x] Add a image manager field into the Event's new, show and edit views.
- [x] Quickly test the Active Storage images management system.
- [x] Verify and ensure that the event's images management works.
```
