### ISSUE TITLE
Add images uploading and management support to Event model

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#37]
Modify User model in order to add images management support with Active Storage.
```[tasklist]
### Tasks
- [ ] Verify that Active Storage is previously installed in the project.
- [ ] Add a User model migration to add a image field support.
- [ ] Add a image manager field into the Event's new, show and edit views.
- [ ] Verify that the event's images management works.
```
