### ISSUE TITLE
Add username to Devise's User model and private/public events

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#38]
Add a username field to Devise's User model.
```[tasklist]
### Tasks
- [x] Add username field into Devise's User model
- [x] Generate the database migration.
- [x] Implement an username printing system into the navbar.
- [x] Implement an implicit Event-User relationship in the events creation system.
- [x] Add a boolean public field into the Event model.
- [x] Generate a database migration.
- [x] Add a public checkbox into Event model's new and edit views.
```
