### ISSUE TITLE
Add a public/private feature into Event model

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#39]
Incorporate a private/public option into Event model.

```[tasklist]
### Tasks
- [ ] Add a public field into the Event model.
- [ ] Generate a database migration.
- [ ] Add a private/public select field into Event model's new and edit views.
```
