### ISSUE TITLE
Add an events filtering system

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#41]
Design and implement an events filtering system, allowing any logged user to search events by their type (private/public) and date (range or a specific one).
```[tasklist]
### Tasks
- [x] Add a default events filtering by current user and public type.
- [x] Add a private/public events filtering.
- [x] Add events filtering by dates (specific values or ranges).
```
