### ISSUE TITLE
Add an events pagination system

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#42]
Code and implement a pagination systems for events index view, this in order to achieve a overall better navigation experience.
```[tasklist]
### Tasks
- [x] Install Pagy gem in the projects
- [x] Make the necessary configuration in order to show maximum 10 events at the same time.
- [x] Setup the necessary db seed values in order to properly test pagination system.
- [x] Ensure the pagination system works properly.
```
