### ISSUE TITLE
Build all the Unit testing for updated Event's model and controller

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#43]
Modify all the Event's model and controller tests in order to assure the correct functionality of new features..

```[tasklist]
### Tasks
- [x] Modify the Event's tests to assert the correct functionality of new features.
- [x] Setup RuboCop and use it to analyze the test code.
- [x] Setup Reek and use it to detect any test code smells.
- [x] Achieve an overall 80 minimum RubyCritic score and improve test code quality.
```
