### ISSUE TITLE
Build an automatic event's emails notifitication system

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#56]
Add a feature that allows the users to set specific dates to their events in order to be automatically notificated about them via email address.
```[tasklist]
### Tasks
- [x] Add a new date field in Event model and views to register a notification date.
- [x] Install and configure Active Job.
- [x] Install and configure Sidekiq.
- [x] Make the application automatically send events notifications emails when it corresponds.
```
