### ISSUE TITLE
Style all the Devise's generated password resetting and email confirmation views

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#60]
Use Tailwind CSS to appropiately style all the Devise's generated password resetting and email confirmation views.
```[tasklist]
### Tasks
- [x] Style Devise's confirmation new view.
- [x] Style Devise's password new view.
- [x] Style Devise's password edit view.
```
