### ISSUE TITLE
Update Unit tests

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#61]
Update event's model and controller tests in order to test events mailing and background jobs.

```[tasklist]
### Tasks
- [x] Properly update the events tests.
- [x] Generate the events mailing tests.
- [x] Generate the events job tests.
```
