### ISSUE TITLE
Improve events UI's styles

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#67]
Generate more styled events UI's.
```[tasklist]
### Tasks
- [x] Improve events index UI.
- [x] Improve events show UI.
- [x] Improve events new/edit form UI.
- [ ] Achieve an overall responsive design.
```
