### ISSUE TITLE
Create Rails project template

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#71]
Create Rails project in order to start the entire application's development.
```[tasklist]
### Tasks
- [ ] Initialize Rails project template.
- [ ] Configure the project in order to use PostgreSQL.
- [ ] Ensure that the project can be successfully runned.
```
