### ISSUE TITLE
Code events model and controller tests

### ISSUE THREAD

**Issue by ErikGmz** [BrightCoders-Institute/s5a1-administrador-de-eventos-team01-s5a1#9]
Prepare the testing environment, setup all the necessary data to perform the basic database testing operations and code all the necessary units tests in order to assert the correct events model and controller functionality.

```[tasklist]
### Tasks
- [x] Setup the necessary configuration to make the testing environment work.
- [x] Specify the database default values through the events.yml Rails file.
- [x] Write all units tests of events model and controller.
- [x] Assert that all written tests successfully work.
- [x] Setup RuboCop and use it to analyze the test code.
- [x] Setup Reek and use it to detect any test code smells.
- [x] Achieve an overall 65 minimum RubyCritic score and improve test code quality.
```
